In [ ]:
x = 7
z = x * 2
print(z)

14


In [ ]:
name = "Bipul"
print(name*2)

BipulBipul


In [ ]:
salaries = [5043,6773,7656,2338,4567]

print(salaries)
print(salaries * 2)

[5043, 6773, 7656, 2338, 4567]
[5043, 6773, 7656, 2338, 4567, 5043, 6773, 7656, 2338, 4567]


In [ ]:
for salary in salaries:
  print(salary*2)

10086
13546
15312
4676
9134


In [ ]:
import numpy as np

salaries = np.array([5043,6773,7656,2338,4567])
print(salaries)

[5043 6773 7656 2338 4567]


In [ ]:
print(salaries * 2)

[10086 13546 15312  4676  9134]


In [ ]:
n2 = np.array([[2,3,4,1,6] , [3,6,2,7,8] , [2,6,8,9,5]])
print(n2)

[[2 3 4 1 6]
 [3 6 2 7 8]
 [2 6 8 9 5]]


**Broadcasting**

In [ ]:
print(n2*3)

[[ 6  9 12  3 18]
 [ 9 18  6 21 24]
 [ 6 18 24 27 15]]


In [ ]:
n3 = np.array([2,3,2,3,2])
print(n3)

[2 3 2 3 2]


In [ ]:
print(n2 * n3)

[[ 4  9  8  3 12]
 [ 6 18  4 21 16]
 [ 4 18 16 27 10]]


In [ ]:
n4 = np.array([[2],[3],[2]])
print(n4)

[[2]
 [3]
 [2]]


In [ ]:
print(n2)

[[2 3 4 1 6]
 [3 6 2 7 8]
 [2 6 8 9 5]]


In [ ]:
print(n2*n4)

[[ 4  6  8  2 12]
 [ 9 18  6 21 24]
 [ 4 12 16 18 10]]


In [ ]:
n5 = np.array([[3,2,4,2,2] , [2,4,3,2,2],[5,4,5,4,3]])
print(n5)

[[3 2 4 2 2]
 [2 4 3 2 2]
 [5 4 5 4 3]]


In [ ]:
print(n2*n5)

[[ 6  6 16  2 12]
 [ 6 24  6 14 16]
 [10 24 40 36 15]]


In [ ]:
n6 = np.array([[3,2,4,2,2] , [2,4,3,2,2]])
print(n2*n6)

ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 

In [ ]:
a = np.array([4,3,5,6,1])
print(a)
print()
print(a.ndim)
print(a.shape)

[4 3 5 6 1]

1
(5,)


In [ ]:
b = np.array([[4,3,5,6,1]])
print(b)
print()
print(b.ndim)
print(b.shape)

[[4 3 5 6 1]]

2
(1, 5)


**dimensions of numpy array**

In [ ]:
n1 = np.array([4,3,5,6,1])
print(n1)
print()
print(n1.ndim)
print(n1.shape)
print(n1.size)

[4 3 5 6 1]

1
(5,)
5


In [ ]:
n2 = np.array([[3,2,5,3,2],[3,2,4,3,2],[4,3,2,4,6]])
print(n2)
print()
print(n2.ndim)
print(n2.shape)
print(n2.size)

[[3 2 5 3 2]
 [3 2 4 3 2]
 [4 3 2 4 6]]

2
(3, 5)
15


In [ ]:
n3 = np.array([[[3,2,5,3,2],[3,2,4,3,2],[4,3,2,4,6]] , [[2,1,3,1,2],[4,3,2,1,2],[4,5,6,7,8]]])
print(n3)

[[[3 2 5 3 2]
  [3 2 4 3 2]
  [4 3 2 4 6]]

 [[2 1 3 1 2]
  [4 3 2 1 2]
  [4 5 6 7 8]]]


In [ ]:
print(n3.ndim)
print(n3.shape)
print(n3.size)

3
(2, 3, 5)
30


In [ ]:
print(n1)

[4 3 5 6 1]


In [ ]:
print(n1[2])

5


In [ ]:
print(np.where(n1 == 6))

(array([3]),)


In [ ]:
print(n2)

[[3 2 5 3 2]
 [3 2 4 3 2]
 [4 3 2 4 6]]


In [ ]:
print(n2[0,0])
print(n2[2,0])
print(n2[1,3])

3
4
3


In [ ]:
print(np.where(n2 == 2))

(array([0, 0, 1, 1, 2]), array([1, 4, 1, 4, 2]))


In [ ]:
print(n3)

[[[3 2 5 3 2]
  [3 2 4 3 2]
  [4 3 2 4 6]]

 [[2 1 3 1 2]
  [4 3 2 1 2]
  [4 5 6 7 8]]]


In [ ]:
print(n3[0,2,4])

6


In [ ]:
np.where(n3 == 8)

(array([1]), array([2]), array([4]))

**Slicing of an array**

In [ ]:
n1 = np.array([4,3,5,6,1])
print(n1[1:4])

[3 5 6]


In [ ]:
print(n1[2:5])

[5 6 1]


In [ ]:
print(n1[2:])

[5 6 1]


In [ ]:
n2 = np.array([[3,2,5,3,2],[3,2,4,3,2],[4,3,2,4,6]])
print(n2)

[[3 2 5 3 2]
 [3 2 4 3 2]
 [4 3 2 4 6]]


In [ ]:
print(n2[1:3, 1:4])

[[2 4 3]
 [3 2 4]]


In [ ]:
print(n2[:, 4:])

[[2]
 [2]
 [6]]


In [ ]:
print(n2[:, 3:5])

[[3 2]
 [3 2]
 [4 6]]


In [ ]:
print(n2[: , -1:])

[[2]
 [2]
 [6]]


In [ ]:
print(n2)

[[3 2 5 3 2]
 [3 2 4 3 2]
 [4 3 2 4 6]]


In [ ]:
print(n2[:,3:])

[[3 2]
 [3 2]
 [4 6]]


In [ ]:
print(n2[:,-2:])

[[3 2]
 [3 2]
 [4 6]]


In [ ]:
print(n2)

[[3 2 5 3 2]
 [3 2 4 3 2]
 [4 3 2 4 6]]


In [ ]:
print(np.sum(n2))
print(np.prod(n2))
print(np.mean(n2))
print(np.std(n2))
print(np.min(n2))
print(np.max(n2))
print(np.argmin(n2))
print(np.argmax(n2))

48
14929920
3.2
1.1661903789690602
2
6
1
14


In [ ]:
print(n2)

[[3 2 5 3 2]
 [3 2 4 3 2]
 [4 3 2 4 6]]


In [ ]:
print(np.sum(n2, axis=0))
print(np.prod(n2, axis=0))
print(np.mean(n2, axis=0))
print(np.std(n2, axis=0))
print(np.min(n2, axis=0))
print(np.max(n2, axis=0))
print(np.argmin(n2, axis=0))
print(np.argmax(n2, axis=0))

[10  7 11 10 10]
[36 12 40 36 24]
[3.33333333 2.33333333 3.66666667 3.33333333 3.33333333]
[0.47140452 0.47140452 1.24721913 0.47140452 1.88561808]
[3 2 2 3 2]
[4 3 5 4 6]
[0 0 2 0 0]
[2 2 0 2 2]


In [ ]:
print(np.sum(n2, axis=1))
print(np.prod(n2, axis=1))
print(np.mean(n2, axis=1))
print(np.std(n2, axis=1))
print(np.min(n2, axis=1))
print(np.max(n2, axis=1))
print(np.argmin(n2, axis=1))
print(np.argmax(n2, axis=1))

[15 14 19]
[180 144 576]
[3.  2.8 3.8]
[1.09544512 0.74833148 1.32664992]
[2 2 2]
[5 4 6]
[1 1 2]
[2 2 4]


In [ ]:
print(n3)

[[[3 2 5 3 2]
  [3 2 4 3 2]
  [4 3 2 4 6]]

 [[2 1 3 1 2]
  [4 3 2 1 2]
  [4 5 6 7 8]]]


In [ ]:
print(np.sum(n3))

99


In [ ]:
print(np.sum(n3 , axis = 0))

[[ 5  3  8  4  4]
 [ 7  5  6  4  4]
 [ 8  8  8 11 14]]


In [ ]:
print(np.sum(n3 , axis = 1))      #for each column

[[10  7 11 10 10]
 [10  9 11  9 12]]


In [ ]:
print(np.sum(n3 , axis = 2))      #for each row

[[15 14 19]
 [ 9 12 30]]


In [ ]:
print(n3)

[[[3 2 5 3 2]
  [3 2 4 3 2]
  [4 3 2 4 6]]

 [[2 1 3 1 2]
  [4 3 2 1 2]
  [4 5 6 7 8]]]


**more functions of numpy**

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.ones((4,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.arange(0,36)

In [ ]:
#reshaping of an array -36 - (1,36) , (36,1) , (2,18) , (18,2) , (3,12) , (12,3) , (4,9) , (9,4), (6,6)

b = a.reshape(6,6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
np.linspace(0,10,7)       #equally spaced 7 values between 0 to 10

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

**dot product**

In [ ]:
X1 = np.array([[3,2,4,5] , [3,2,5,6] , [4,3,2,1]])
print(X1)

[[3 2 4 5]
 [3 2 5 6]
 [4 3 2 1]]


In [ ]:
X2 = np.array([[1,2,3,4,5,6,7,2]]).reshape(4,2)
X2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 2]])

In [ ]:
print(np.dot(X1,X2))

[[64 48]
 [76 56]
 [30 34]]


* 2x + 2y + z = 7
* x + y + z = 5
* 3x + y + 2z = 15

In [ ]:
A = np.array([[2,2,1],[1,1,1],[3,1,2]])
print(A)

[[2 2 1]
 [1 1 1]
 [3 1 2]]


In [ ]:
X = np.array([['x'] , ['y'] , ['z']])
print(X)

[['x']
 ['y']
 ['z']]


In [ ]:
B = np.array([[7],[5],[15]])
print(B)

[[ 7]
 [ 5]
 [15]]


In [ ]:
#A.X = B
#X = inv(A).B

Ainv = np.linalg.inv(A)
X = np.dot(Ainv , B)
print(X)

[[ 3.5]
 [-1.5]
 [ 3. ]]


* masking

In [ ]:
a = np.array([12, 20, 23, 15, 25])

print(a > 20)

[False False  True False  True]


In [ ]:
a = np.array([12, 20, 23, 15, 25])

print(a[a > 20])

[23 25]


* Fancy index

In [ ]:
a = np.array([12, 20, 23, 15, 25 , 29])

print(a[[1,3,5]])

[20 15 29]


In [ ]:
a[1]

np.int64(20)

* conditional replacement

In [ ]:
a = np.array([12, 20, 23, 15, 25 , 29])

a[5] = 35

print(a)

[12 20 23 15 25 35]


In [ ]:
a[a > 25] = 25
print(a)

[12 20 23 15 25 25]


In [ ]:
a = np.array([12, 20, 23, 15, 25 , 29])

np.sort(a)

print(a)

[12 20 23 15 25 29]


In [ ]:
print(n2)

[[3 2 5 3 2]
 [3 2 4 3 2]
 [4 3 2 4 6]]


In [ ]:
n3 = np.sort(n2, axis=0)
print(n3)

[[3 2 2 3 2]
 [3 2 4 3 2]
 [4 3 5 4 6]]


In [ ]:
n4 = np.sort(n2, axis=1)
print(n4)

[[2 2 3 3 5]
 [2 2 3 3 4]
 [2 3 4 4 6]]


In [ ]:
print(a)
a_reverse = np.flip(a)
print(a_reverse)

[12 20 23 15 25 29]
[29 25 15 23 20 12]


* random values matrix

In [ ]:
nr1 = np.random.rand()
print(nr1)

0.9202966610506603


In [ ]:
nr2 = np.random.randint(10,200)
print(nr2)

137


In [ ]:
nr3 = np.random.randint(10,200, (4,6))
print(nr3)

[[ 86 132  73  82 117 163]
 [ 68  52 191 191  91 198]
 [ 62  40 164  62  50 103]
 [129 170 195  80 193  51]]


In [ ]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])