**exception handling**

In [1]:
myfile = open('/content/example.txt' , 'r')   #open the file
print(myfile.read())                            #read the file content
myfile.close()                                  #close the file

FileNotFoundError: [Errno 2] No such file or directory: '/content/example.txt'

In [2]:
try:
  pass
except:
  pass

In [5]:
try:
  print(x)
except Exception as err:
  print(err)

name 'x' is not defined


In [7]:
a = 5
try:
  print(a)
except Exception as err:
  print(err)

5


In [6]:
try:
  myfile = open('/content/example.txt' , 'r')   #open the file
  print(myfile.read())                            #read the file content
  myfile.close()                                  #close the file
except Exception as err:
  print(err)

[Errno 2] No such file or directory: '/content/example.txt'


**Object-Oriented Programming**

In [35]:
def visitors():
  name = "Ajay Sahrma"
  return name

In [36]:
visitors()

'Ajay Sahrma'

In [37]:
class visitor_details:
  name = "Ajay Sharma"                        #attribute of class which defines property

  def say_hello(self):                         #method of class which defines behavior
    print("Hello" , visitor_details.name)

  def say_goodbye(self):
    print("Goodbye" , visitor_details.name)

In [47]:
v = visitor_details()
print(v.name)

Ajay Sharma


In [39]:
v.say_hello()

Hello Ajay Sharma


In [40]:
v.say_goodbye()

Goodbye Ajay Sharma


* Constructor or Initiliser in class

In [77]:
class employess:
  def __init__(self,name,location):            #method of class that executes automatically when we create object of class
    self.emp_name = name                       #self - refer the instance of the class, it differentiate between local and instance-specific data
    self.emp_location = location


  def show_employee_details(self):
    emp_name = "Ramesh"
    emp_location = "Jaipur"
    details_local = {"Name" : emp_name , "Location" : emp_location}
    details_instance_specific = {"Name" : self.emp_name , "Location" : self.emp_location}
    return details_local , details_instance_specific

In [78]:
e1 = employess("Rahul" , "Delhi")             #object or instance of class
e2 = employess("Gagan" , "Mysore")
e3 = employess("Pavan" , "Mumbai")

In [79]:
print(e1.emp_name)
print(e1.emp_location)
e1.show_employee_details()

Rahul
Delhi


({'Name': 'Ramesh', 'Location': 'Jaipur'},
 {'Name': 'Rahul', 'Location': 'Delhi'})

In [80]:
print(e2.emp_name)
print(e2.emp_location)
e2.show_employee_details()

Gagan
Mysore


({'Name': 'Ramesh', 'Location': 'Jaipur'},
 {'Name': 'Gagan', 'Location': 'Mysore'})

In [81]:
print(e3.emp_name)
print(e3.emp_location)

e3.show_employee_details()

Pavan
Mumbai


({'Name': 'Ramesh', 'Location': 'Jaipur'},
 {'Name': 'Pavan', 'Location': 'Mumbai'})

In [89]:
#class calculator
#- attributes - num_1, num_2
#- methods - sum() , difference() , divide(), multiply()

class calculator:
  def __init__(self,a,b):
    self.num_1 = a
    self.num_2 = b

  def sum(self):
    return self.num_1 + self.num_2

  def difference(self):
    return self.num_1 - self.num_2

  def divide(self):
    return self.num_1 / self.num_2

  def multiply(self):
    return self.num_1 * self.num_2

In [90]:
c1 = calculator(8,4)
print(c1.sum())
print(c1.difference())
print(c1.divide())
print(c1.multiply())

12
4
2.0
32


In [91]:
c2 = calculator(3456, 43)
print(c2.sum())
print(c2.difference())
print(c2.divide())
print(c2.multiply())

3499
3413
80.37209302325581
148608


****
****
**Packages and modules of Python for Data Science & Machine Learning**

    * Numpy
    * Pandas
    * Matplotlib
****
****

**Numpy**

  - Numerical python
  - Numerical operations on n-dimensional data

In [92]:
a = 5
print(a * 2)

10


In [93]:
b = [3,4,5,6,7]
print(b * 2)

[3, 4, 5, 6, 7, 3, 4, 5, 6, 7]


In [94]:
import numpy as np

n1 = np.array([3,4,5,6,7])

print(n1 * 2)

[ 6  8 10 12 14]


In [96]:
print(n1.shape)
print(n1.ndim)

(5,)
1


In [98]:
n2 = np.array([[3,4,5,6,7] , [12,13,19,11,10] , [8,9,5,2,1]])
print(n2)

[[ 3  4  5  6  7]
 [12 13 19 11 10]
 [ 8  9  5  2  1]]


In [99]:
print(n2.shape)
print(n2.ndim)

(3, 5)
2


In [100]:
print(n2[0,0])

3


In [101]:
print(n2[1,0])

12


In [102]:
print(np.sum(n2))
print(np.prod(n2))
print(np.mean(n2))
print(np.std(n2))
print(np.max(n2))
print(np.min(n2))
print(np.argmax(n2))
print(np.argmin(n2))

115
591566976000
7.666666666666667
4.642796092394707
19
1
7
14


In [103]:
print(n2)

[[ 3  4  5  6  7]
 [12 13 19 11 10]
 [ 8  9  5  2  1]]


In [104]:
#Calculate for each column
print(np.sum(n2 , axis = 0))
print(np.prod(n2 , axis = 0))
print(np.mean(n2 , axis = 0))
print(np.std(n2 , axis = 0))
print(np.max(n2 , axis = 0))
print(np.min(n2 , axis = 0))
print(np.argmax(n2 , axis = 0))
print(np.argmin(n2 , axis = 0))

[23 26 29 19 18]
[288 468 475 132  70]
[7.66666667 8.66666667 9.66666667 6.33333333 6.        ]
[3.68178701 3.68178701 6.59966329 3.68178701 3.74165739]
[12 13 19 11 10]
[3 4 5 2 1]
[1 1 1 1 1]
[0 0 0 2 2]


In [105]:
#Calculate for each row
print(np.prod(n2 , axis = 1))
print(np.mean(n2 , axis = 1))
print(np.std(n2 , axis = 1))
print(np.max(n2 , axis = 1))
print(np.min(n2 , axis = 1))
print(np.argmax(n2 , axis = 1))
print(np.argmin(n2 , axis = 1))

[  2520 326040    720]
[ 5. 13.  5.]
[1.41421356 3.16227766 3.16227766]
[ 7 19  9]
[ 3 10  1]
[4 2 1]
[0 4 4]
